inherit_from:
  - https://dev.k.io/rubocop/rubocop.yml

AllCops:
  TargetRubyVersion: 2.5

Metrics/ModuleLength:
  Enabled: false

Metrics/AbcSize:
  Max: 60

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/ClassLength:
  Enabled: false

Lint/MissingSuper:
  Enabled: false
